# Generated by Django 5.1.1 on 2024-09-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('contacts', models.JSONField()),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('updatedAt', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
